version: '3.8'

# TODO : Specify docker image version of each service instead of using 'latest'

services:
  wp:
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    ports:
      - ${IP}:${WP_PORT}:80 # change ip if required
    volumes:
      - ${DATA_DIR}/wp/config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ${DATA_DIR}/wp/wp-app:/var/www/html # Full wordpress project
      #- ${DATA_DIR}/wp/plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ${DATA_DIR}/wp/theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: ${DB_ROOT_USER}
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db
    links:
      - db

  wpcli:
    image: wordpress:cli
    volumes:
      - ${DATA_DIR}/wp/config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ${DATA_DIR}/wp/wp-app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: ${DB_ROOT_USER}
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db
      - wp

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: ${DB_PORT}
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - ${IP}:${PMA_PORT}:80
    links:
      - db:db

  db:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - 127.0.0.1:${DB_PORT}:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ${DATA_DIR}/wp-data:/docker-entrypoint-initdb.d
      - ${DATA_DIR}/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

volumes:
  db_data: